--Creación de la base de datos
CREATE DATABASE PRUEBATECNICAYANETHROMERO
--
GO
--1
USE PRUEBATECNICAYANETHROMERO
--
GO
-- Creación de la tabla maestra que almacenará los tipos de identificación
CREATE TABLE TIPOIDENTIFICACION(ID_TIPOIDENTIFICACION INT IDENTITY PRIMARY KEY,
								NOMBRE			      NVARCHAR(100)
								)
-- Insertamos valores de prueba
INSERT INTO TIPOIDENTIFICACION(NOMBRE) VALUES ('Cédula'), ('NIT'), ('NUIP'), ('Pasaporte')
--
CREATE TABLE CONTACTO(ID_CONTACTO INT IDENTITY PRIMARY KEY,
					  CODTIPOIDENTIFICACION	INT           ,
					  NUMERODOCUMENTO       NVARCHAR(100) ,
					  NOMBRES			    NVARCHAR(75)  ,
					  APELLIDOS             NVARCHAR(75) ,
					  MENSAJE               NVARCHAR(MAX)    ,
					  CONSTRAINT FK_CONTACTO_TIPOIDENTIFICACION FOREIGN KEY(CODTIPOIDENTIFICACION)
					  REFERENCES TIPOIDENTIFICACION(ID_TIPOIDENTIFICACION)
								)
