//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contacto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTO
    {
        public int ID_CONTACTO { get; set; }
        public Nullable<int> CODTIPOIDENTIFICACION { get; set; }
        public string NUMERODOCUMENTO { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string MENSAJE { get; set; }
    
        public virtual TIPOIDENTIFICACION TIPOIDENTIFICACION { get; set; }
    }
}
